[[headers]]
    for = "/wiki/*"
    [headers.values]
        Content-Type = "text/html; charset=utf8"

####################################################################
#   See content-type/README for details on these

[[headers]]
    for = "/content-type/lower/*"
    [headers.values]
        content-type = "text/html; charset=utf8"

[[headers]]
    for = "/content-type/mixed/*"
    [headers.values]
        Content-type = "text/html; charset=utf8"

[[headers]]
    for = "/content-type/upper/*"
    [headers.values]
        Content-Type = "text/html; charset=utf8"

####################################################################
#   protected/
#
#   Though the deploy summary says "All header rules deployed without
#   errors," authentication isn't requested or required. Seems it only
#   works on paid accounts, as documented here:
#     https://www.netlify.com/blog/2017/04/07/selective-password-protection/

[[headers]]
    for = "/protected/*"
    [headers.values]
        Basic-Auth = "user1:one user2:two"
